import React from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Mail, CheckCircle, Clock } from 'lucide-react';
import { Badge } from '@/components/ui/badge';

function EmailLogList({ logs }) {
  if (!logs || logs.length === 0) {
    return (
      <div className="bg-white rounded-xl shadow-lg border border-slate-200 p-12 text-center text-slate-500">
        <div className="flex justify-center mb-4">
          <div className="p-4 bg-slate-50 rounded-full">
            <Mail className="w-8 h-8 text-slate-400" />
          </div>
        </div>
        <h3 className="text-lg font-medium text-slate-900">No Email Logs</h3>
        <p className="mt-1">Email reminders generated by the system will appear here.</p>
      </div>
    );
  }

  return (
    <div className="bg-white rounded-xl shadow-lg border border-slate-200 overflow-hidden">
      <div className="p-6 border-b border-slate-200 bg-slate-50/50">
        <h2 className="text-lg font-semibold text-slate-800">Email Reminder Logs</h2>
        <p className="text-sm text-slate-500">History of automated reminders sent to customers.</p>
      </div>
      <div className="overflow-x-auto">
        <table className="w-full">
          <thead>
            <tr className="border-b border-slate-200 bg-slate-50/50">
              <th className="text-left py-3 px-6 text-xs font-semibold text-slate-500 uppercase tracking-wider">Time Sent</th>
              <th className="text-left py-3 px-6 text-xs font-semibold text-slate-500 uppercase tracking-wider">Recipient</th>
              <th className="text-left py-3 px-6 text-xs font-semibold text-slate-500 uppercase tracking-wider">Product</th>
              <th className="text-left py-3 px-6 text-xs font-semibold text-slate-500 uppercase tracking-wider">Expiry Context</th>
              <th className="text-left py-3 px-6 text-xs font-semibold text-slate-500 uppercase tracking-wider">Status</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-slate-100">
            <AnimatePresence>
              {logs.map((log, index) => (
                <motion.tr
                  key={log.id}
                  initial={{ opacity: 0, x: -20 }}
                  animate={{ opacity: 1, x: 0 }}
                  transition={{ delay: index * 0.05 }}
                  className="hover:bg-slate-50 transition-colors"
                >
                  <td className="py-4 px-6 whitespace-nowrap">
                    <div className="flex flex-col">
                      <span className="text-sm font-medium text-slate-900">
                        {new Date(log.sentAt).toLocaleDateString()}
                      </span>
                      <span className="text-xs text-slate-500">
                        {new Date(log.sentAt).toLocaleTimeString()}
                      </span>
                    </div>
                  </td>
                  <td className="py-4 px-6">
                    <div className="flex flex-col">
                      <span className="text-sm font-medium text-slate-900">{log.customerName}</span>
                      <span className="text-xs text-slate-500">{log.customerEmail}</span>
                    </div>
                  </td>
                  <td className="py-4 px-6 text-sm text-slate-700">
                    {log.productName}
                  </td>
                  <td className="py-4 px-6">
                    <div className="flex flex-col text-xs">
                      <span className="text-slate-600">Expires: {new Date(log.expiryDate).toLocaleDateString()}</span>
                      <span className="font-medium text-amber-600">{log.daysLeft} days remaining</span>
                    </div>
                  </td>
                  <td className="py-4 px-6">
                    <Badge variant={log.status === 'Sent' ? 'success' : 'secondary'} className="flex w-fit items-center gap-1">
                      {log.status === 'Sent' ? <CheckCircle className="w-3 h-3" /> : <Clock className="w-3 h-3" />}
                      {log.status}
                    </Badge>
                  </td>
                </motion.tr>
              ))}
            </AnimatePresence>
          </tbody>
        </table>
      </div>
    </div>
  );
}

export default EmailLogList;